Connected to Python 3.14.7

In [ ]:
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)

In [ ]:
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
df.head(5)

shape: (5, 17)
┌────────────┬────────────┬─────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ airport_co ┆ airport_na ┆ month   ┆ year ┆ … ┆ minutes_de ┆ minutes_de ┆ minutes_de ┆ minutes_de │
│ de         ┆ me         ┆ ---     ┆ ---  ┆   ┆ layed_nas  ┆ layed_secu ┆ layed_weat ┆ layed_tota │
│ ---        ┆ ---        ┆ str     ┆ i64  ┆   ┆ ---        ┆ rity       ┆ her        ┆ l          │
│ str        ┆ str        ┆         ┆      ┆   ┆ i64        ┆ ---        ┆ ---        ┆ ---        │
│            ┆            ┆         ┆      ┆   ┆            ┆ i64        ┆ i64        ┆ i64        │
╞════════════╪════════════╪═════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ ATL        ┆ Atlanta,   ┆ January ┆ 2005 ┆ … ┆ 207467     ┆ 297        ┆ 36931      ┆ 465533     │
│            ┆ GA: Hartsf ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│            ┆ ield-Jacks ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│            ┆ o…         ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│ DEN        ┆ Denver,    ┆ January ┆ 2005 ┆ … ┆ 36817      ┆ 363        ┆ 21779      ┆ 182797     │
│            ┆ CO: Denver ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│            ┆ Internatio ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│            ┆ n…         ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│ IAD        ┆            ┆ January ┆ 2005 ┆ … ┆ 35660      ┆ 208        ┆ 4497       ┆ 134881     │
│ ORD        ┆ Chicago,   ┆ January ┆ 2005 ┆ … ┆ 364382     ┆ 151        ┆ 24859      ┆ 638894     │
│            ┆ IL:        ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│            ┆ Chicago    ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│            ┆ O'Hare In… ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│ SAN        ┆ San Diego, ┆ January ┆ 2005 ┆ … ┆ 21127      ┆ 218        ┆ 4326       ┆ 91552      │
│            ┆ CA: San    ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│            ┆ Diego      ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
│            ┆ Inter…     ┆         ┆      ┆   ┆            ┆            ┆            ┆            │
└────────────┴────────────┴─────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [ ]:
# Include and execute your code here
df = df.with_columns(
pl.when(pl.col("month").is_in(["January", "Febuary", "March"])).then(pl.lit("Winter"))
.when(pl.col("month").is_in(["April", "May", "June"])).then(pl.lit("Spring"))
.when(pl.col("month").is_in(["July", "August", "September"])).then(pl.lit("Summer"))
.when(pl.col("month").is_in(["October", "November", "December"])).then(pl.lit("Fall"))
.otherwise(pl.lit("Unknown"))
.alias("season")
)

In [ ]:
# Include and execute your code here
df.filter(
    (pl.col("num_of_delays_weather") != "-999") &
    (pl.col("num_of_delays_weather") != "1500") &
    (pl.col("num_of_delays_nas") != "-999") &
    (pl.col("num_of_delays_nas") != "1500") &
    (pl.col("num_of_delays_late_aircraft") != "-999") &
    (pl.col("num_of_delays_late_aircraft") != "1500")
)

.(pl.col("^num_of_.*$").cast(pl.Float64) / 1000)

SyntaxError: invalid syntax (<ipython-input-4-79c0ecd02b33>, line 11)

In [ ]:
# Include and execute your code here
# Questão 3
df = df.with_columns(
    (
        pl.col("num_of_delays_weather") + 
(pl.col("num_of_delays_late_aircraft") * 0.30) + 
 pl.when(pl.col("month").is_in(["April", "May", "June", "July", "August"]))
  .then(pl.col("num_of_delays_nas") * 0.40)
        .otherwise(pl.col("num_of_delays_nas") * 0.65)
    ).alias("total_weather_delays")
)


df.head(5)

shape: (5, 19)
┌─────────────┬─────────────┬─────────┬──────┬───┬─────────────┬─────────────┬────────┬────────────┐
│ airport_cod ┆ airport_nam ┆ month   ┆ year ┆ … ┆ minutes_del ┆ minutes_del ┆ season ┆ total_weat │
│ e           ┆ e           ┆ ---     ┆ ---  ┆   ┆ ayed_weathe ┆ ayed_total  ┆ ---    ┆ her_delays │
│ ---         ┆ ---         ┆ str     ┆ i64  ┆   ┆ r           ┆ ---         ┆ str    ┆ ---        │
│ str         ┆ str         ┆         ┆      ┆   ┆ ---         ┆ i64         ┆        ┆ f64        │
│             ┆             ┆         ┆      ┆   ┆ i64         ┆             ┆        ┆            │
╞═════════════╪═════════════╪═════════╪══════╪═══╪═════════════╪═════════════╪════════╪════════════╡
│ ATL         ┆ Atlanta,    ┆ January ┆ 2005 ┆ … ┆ 36931       ┆ 465533      ┆ Winter ┆ 3137.0     │
│             ┆ GA: Hartsfi ┆         ┆      ┆   ┆             ┆             ┆        ┆            │
│             ┆ eld-Jackso… ┆         ┆      ┆   ┆             ┆             ┆        ┆            │
│ DEN         ┆ Denver, CO: ┆ January ┆ 2005 ┆ … ┆ 21779       ┆ 182797      ┆ Winter ┆ 1119.15    │
│             ┆ Denver Inte ┆         ┆      ┆   ┆             ┆             ┆        ┆            │
│             ┆ rnation…    ┆         ┆      ┆   ┆             ┆             ┆        ┆            │
│ IAD         ┆             ┆ January ┆ 2005 ┆ … ┆ 4497        ┆ 134881      ┆ Winter ┆ 960.15     │
│ ORD         ┆ Chicago,    ┆ January ┆ 2005 ┆ … ┆ 24859       ┆ 638894      ┆ Winter ┆ 4502.25    │
│             ┆ IL: Chicago ┆         ┆      ┆   ┆             ┆             ┆        ┆            │
│             ┆ O'Hare In…  ┆         ┆      ┆   ┆             ┆             ┆        ┆            │
│ SAN         ┆ San Diego,  ┆ January ┆ 2005 ┆ … ┆ 4326        ┆ 91552       ┆ Winter ┆ 674.7      │
│             ┆ CA: San     ┆         ┆      ┆   ┆             ┆             ┆        ┆            │
│             ┆ Diego       ┆         ┆      ┆   ┆             ┆             ┆        ┆            │
│             ┆ Inter…      ┆         ┆      ┆   ┆             ┆             ┆        ┆            │
└─────────────┴─────────────┴─────────┴──────┴───┴─────────────┴─────────────┴────────┴────────────┘

In [ ]:
# Include and execute your code here

# Questão 4
grafic = (
ggplot(df, aes(x='season', y='total_weather_delays')) + 
geom_boxplot() + labs(title="Distribution of Weather Delays by Season", x="Season of the Year", y="Total Delays in thousands"))

grafic.show()

In [ ]:
# Include and execute your code here

# Questão 4
grafic = (
ggplot(df, aes(x='season', y='total_weather_delays')) + 
geom_boxplot() + labs(title="Distribution of Weather Delays by Season", x="Season of the Year", y="Total Delays in thousands"))

grafic.show()